<?php

return array(
    'categories_presets' => array(
        0 => array("nav_bg" => "#1e73be",
                    "hide_nav_bg" => "on",
                    "text_bg" => "#82a0bf",
                    "hide_text_bg" => "on",
                    "text_color" => "#1e73be",
                    "padding" => array("vert" => "3",
                                        "hor" => "10"),
                    "font_weight" =>"normal",
                    "font_size" => "12",
                    "border" => array("width" => "1",
                                        "style" => "solid",
                                        "color" =>"#1e73be",
                                        "radius" => "3",
                                        "radius_unit" =>"px")
        ),
        1 => array("nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#000000",
            "padding" => array("vert" => "1",
                "hor" => "10"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "1",
                "style" => "none",
                "color" =>"#b2b2b2",
                "radius" => "3",
                "radius_unit" =>"px")
        ),
        2 => array("nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#0a0a0a",
            "padding" => array("vert" => "1",
                "hor" => "10"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "4",
                "style" => "solid",
                "color" =>"#1e73be",
                "radius" => "20",
                "radius_unit" =>"px")
        ),
        3 => array("nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#1e73be",
            "padding" => array("vert" => "3",
                "hor" => "10"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "1",
                "style" => "solid",
                "color" =>"#000000",
                "radius" => "50",
                "radius_unit" =>"px")
        ),
        4 => array("nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#dd3333",
            "padding" => array("vert" => "3",
                "hor" => "4"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "1",
                "style" => "solid",
                "color" =>"#000000",
                "radius" => "0",
                "radius_unit" =>"px")
        ),
        5 => array("nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#000000",
            "padding" => array("vert" => "6",
                "hor" => "10"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "0",
                "style" => "solid",
                "color" =>"#1e73be",
                "radius" => "40",
                "radius_unit" =>"px")
        )
    ),
);